language: node_js
sudo: true
before_install:
  - sudo apt-get update -q
  - nvm install node
  - nvm use node
install: npm install
script: node build/build.js
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: dist