language: node_js
sudo: true

before_install:
  - sudo apt-get update -q
  - nvm install node
  - nvm use node
  - npm install npm -g
install: npm install

script:
  - npm run test-lib
  - npm run test-components
  - if: type = pull_request || branch = master

before_deploy:
  - npm run build

deploy:
  provider: script
  script: chmod +x ./publish.sh && ./publish.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
