language: node_js
if: type = pull_request || branch = master

before_install:
  - sudo apt-get update -q
  - nvm install node
  - nvm use node
  - npm install npm -g
install: npm install

script:
  - npm run test

notifications:
  email: false
